from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional, List
import httpx
import os
import json
from datetime import datetime

router = APIRouter(prefix="/api/v1/retencoes", tags=["retencoes"])

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")


class DadosNF(BaseModel):
    cliente_id: Optional[str] = None
        cliente_nome: Optional[str] = None
            fornecedor: str
                numero_nf: Optional[str] = None
                    data_emissao: Optional[str] = None
                        competencia: Optional[str] = None
                            valor_bruto: float
                                descricao_servico: str
                                    tipo_servico: str


                                    class RetencaoItem(BaseModel):
                                        tributo: str
                                            incide: bool
                                                aliquota: Optional[float] = None
                                                    base_calculo: Optional[float] = None
                                                        valor: Optional[float] = None
                                                            fundamentacao: str
                                                                observacao: Optional[str] = None


                                                                class ResultadoAnalise(BaseModel):
                                                                    retencoes: List[RetencaoItem]
                                                                        valor_bruto: float
                                                                            total_retencoes: float
                                                                                valor_liquido: float
                                                                                    alertas: List[str]
                                                                                        resumo: str


                                                                                        class AnaliseResponse(BaseModel):
                                                                                            id: str
                                                                                                dados_nf: DadosNF
                                                                                                    resultado: ResultadoAnalise
                                                                                                        criado_em: str
                                                                                                        
                                                                                                        
                                                                                                        _historico: List[dict] = []
                                                                                                        
                                                                                                        
                                                                                                        @router.post("/analisar", response_model=AnaliseResponse)
                                                                                                        async def analisar_retencoes(dados: DadosNF):
                                                                                                            if not ANTHROPIC_API_KEY:
                                                                                                                    raise HTTPException(status_code=500, detail="ANTHROPIC_API_KEY nao configurada")
                                                                                                                    
                                                                                                                        prompt = (
                                                                                                                                "Voce e um contador brasileiro especialista em retencoes tributarias.\n"
                                                                                                                                        "Analise os dados abaixo e determine quais tributos devem ser retidos.\n\n"
                                                                                                                                                f"Prestador: {dados.fornecedor}\n"
                                                                                                                                                        f"Tomador: {dados.cliente_nome or 'Nao informado'}\n"
                                                                                                                                                                f"NF: {dados.numero_nf} | Data: {dados.data_emissao}\n"
                                                                                                                                                                        f"Valor Bruto: R$ {dados.valor_bruto:.2f}\n"
                                                                                                                                                                                f"Servico: {dados.descricao_servico}\n"
                                                                                                                                                                                        f"Tipo: {dados.tipo_servico}\n\n"
                                                                                                                                                                                                "Responda APENAS em JSON:\n"
                                                                                                                                                                                                        '{"retencoes": ['
                                                                                                                                                                                                                '{"tributo":"INSS","incide":true,"aliquota":11.0,"base_calculo":0,"valor":0,"fundamentacao":"Lei 9.711/98","observacao":""},'
                                                                                                                                                                                                                        '{"tributo":"ISS","incide":true,"aliquota":2.0,"base_calculo":0,"valor":0,"fundamentacao":"LC 116/2003","observacao":""},'
                                                                                                                                                                                                                                '{"tributo":"IRRF","incide":false,"aliquota":null,"base_calculo":null,"valor":null,"fundamentacao":"","observacao":""},'
                                                                                                                                                                                                                                        '{"tributo":"PIS","incide":false,"aliquota":null,"base_calculo":null,"valor":null,"fundamentacao":"","observacao":""},'
                                                                                                                                                                                                                                                '{"tributo":"COFINS","incide":false,"aliquota":null,"base_calculo":null,"valor":null,"fundamentacao":"","observacao":""},'
                                                                                                                                                                                                                                                        '{"tributo":"CSLL","incide":false,"aliquota":null,"base_calculo":null,"valor":null,"fundamentacao":"","observacao":""}'
                                                                                                                                                                                                                                                                '],"alertas":[],"resumo":""}\n\n'
                                                                                                                                                                                                                                                                        "REGRAS:\n"
                                                                                                                                                                                                                                                                                "- Simples Nacional: ISS NAO retido (LC 123/2006); PIS/COFINS/CSLL nao retidos\n"
                                                                                                                                                                                                                                                                                        "- INSS 11% em cessao de mao de obra (Lei 9.711/98)\n"
                                                                                                                                                                                                                                                                                                "- IRRF: vigilancia 1%, limpeza 1%, TI 1.5%, consultoria 1.5%\n"
                                                                                                                                                                                                                                                                                                        f"- Use base_calculo={dados.valor_bruto} e calcule valor=base_calculo*aliquota/100\n"
                                                                                                                                                                                                                                                                                                                "- Se nao incide: aliquota=null, base_calculo=null, valor=null"
                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                                                                                                async with httpx.AsyncClient(timeout=60.0) as client:
                                                                                                                                                                                                                                                                                                                                            response = await client.post(
                                                                                                                                                                                                                                                                                                                                                            "https://api.anthropic.com/v1/messages",
                                                                                                                                                                                                                                                                                                                                                                            headers={
                                                                                                                                                                                                                                                                                                                                                                                                "x-api-key": ANTHROPIC_API_KEY,
                                                                                                                                                                                                                                                                                                                                                                                                                    "anthropic-version": "2023-06-01",
                                                                                                                                                                                                                                                                                                                                                                                                                                        "content-type": "application/json",
                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        json={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "model": "claude-haiku-4-5-20251001",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "max_tokens": 2000,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "messages": [{"role": "user", "content": prompt}],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if response.status_code != 200:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    raise HTTPException(status_code=502, detail=f"Erro API Claude: {response.text}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            data = response.json()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    text = data["content"][0]["text"].strip()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if text.startswith("```"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        text = text.split("```")[1]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if text.startswith("json"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    text = text[4:]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if text.endswith("```"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        text = text[:-3]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                parsed = json.loads(text.strip())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        retencoes = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                total_retencoes = 0.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for r in parsed.get("retencoes", []):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    valor = r.get("valor") or 0.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if r.get("incide") and valor:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                total_retencoes += float(valor)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            retencoes.append(RetencaoItem(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            tributo=r["tributo"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            incide=r["incide"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            aliquota=r.get("aliquota"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            base_calculo=r.get("base_calculo"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            valor=r.get("valor"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fundamentacao=r.get("fundamentacao", ""),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            observacao=r.get("observacao"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                resultado = ResultadoAnalise(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            retencoes=retencoes,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        valor_bruto=dados.valor_bruto,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    total_retencoes=round(total_retencoes, 2),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                valor_liquido=round(dados.valor_bruto - total_retencoes, 2),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            alertas=parsed.get("alertas", []),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        resumo=parsed.get("resumo", ""),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        analise_id = f"RET-{datetime.now().strftime('%Y%m%d%H%M%S')}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                criado_em = datetime.now().isoformat()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        _historico.append({"id": analise_id, "dados_nf": dados.dict(), "resultado": resultado.dict(), "criado_em": criado_em})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return AnaliseResponse(id=analise_id, dados_nf=dados, resultado=resultado, criado_em=criado_em)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    except json.JSONDecodeError as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            raise HTTPException(status_code=500, detail=f"Erro JSON: {str(e)}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                except httpx.RequestError as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        raise HTTPException(status_code=502, detail=f"Erro conexao: {str(e)}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @router.get("/historico")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        async def listar_historico():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return {"total": len(_historico), "analises": _historico}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @router.delete("/historico/{analise_id}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            async def deletar_analise(analise_id: str):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                global _historico
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    antes = len(_historico)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        _historico = [a for a in _historico if a["id"] != analise_id]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if len(_historico) == antes:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    raise HTTPException(status_code=404, detail="Analise nao encontrada")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return {"ok": True}
