export const OBRIGACOES_SISTEMA = [
  {
    "id": 2,
    "nome": "Adiantamento Salarial",
    "mininome": "ADMTOSAL",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 3,
    "nome": "APURAÇAO PIS e COFINS",
    "mininome": "APURAÇAO",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 25,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 4,
    "nome": "AVISO DE FÉRIAS",
    "mininome": "AV  FÉRIAS",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 31,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 31",
      "Todo dia 31",
      "Todo dia 31",
      "Todo dia 31",
      "1º dia útil",
      "1º dia útil",
      "1º dia útil",
      "1º dia útil",
      "1º dia útil",
      "1º dia útil",
      "1º dia útil",
      "1º dia útil"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 5,
    "nome": "AVISO PRÉVIO",
    "mininome": "AVISO PREV",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 30,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 30",
      "Todo dia 30",
      "Todo dia 30",
      "Todo dia 30",
      "Todo dia 30",
      "Todo dia 30",
      "Todo dia 30",
      "Todo dia 30",
      "Todo dia 30",
      "Todo dia 30",
      "Todo dia 30",
      "Todo dia 30"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 6,
    "nome": "Balancete 2025",
    "mininome": "BLC",
    "departamento": "Contábil",
    "responsavel": "Carlos Eduardo Araújo Marques Pimentel",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": false,
    "meses": [
      "Não Tem",
      "Não Tem",
      "Todo dia 20",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 7,
    "nome": "Balancete Mensal",
    "mininome": "BLCT",
    "departamento": "Contábil",
    "responsavel": "Carlos Eduardo Araújo Marques Pimentel",
    "dia_vencimento": 25,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": true,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 8,
    "nome": "BOLETO VA",
    "mininome": "VA",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 1,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "1º dia útil",
      "1º dia útil",
      "1º dia útil",
      "1º dia útil",
      "1º dia útil",
      "1º dia útil",
      "1º dia útil",
      "1º dia útil",
      "1º dia útil",
      "1º dia útil",
      "1º dia útil",
      "1º dia útil"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 9,
    "nome": "Carnê Leão",
    "mininome": "Carnê Leão",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 10,
    "nome": "CND - ESTADUAL",
    "mininome": "CND ESTADU",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 5,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": true,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 11,
    "nome": "CND - FEDERAL",
    "mininome": "CND FEDERA",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 5,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": true,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 12,
    "nome": "COAF",
    "mininome": "COAF",
    "departamento": "Contábil",
    "responsavel": "Carlos Eduardo Araújo Marques Pimentel",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Último dia útil",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 13,
    "nome": "Comprovante de Rendimento",
    "mininome": "DIRPF",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Não Tem",
      "Último dia útil",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 14,
    "nome": "Contrato de Trabalho Experiencia",
    "mininome": "Cont Traba",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "20º dia útil",
      "20º dia útil",
      "20º dia útil",
      "20º dia útil",
      "20º dia útil",
      "20º dia útil",
      "20º dia útil",
      "20º dia útil",
      "20º dia útil",
      "20º dia útil",
      "20º dia útil",
      "20º dia útil"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 15,
    "nome": "CONTRIBUIÇÃO ASSITENCIAL",
    "mininome": "CONTRIBUIÇ",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 5,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Não Tem",
      "Não Tem",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 16,
    "nome": "CSRF - Serviços Tomados",
    "mininome": "IRRF PRET",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 17,
    "nome": "DAE - Doméstico",
    "mininome": "DAE",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 7,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 18,
    "nome": "DARF - Cofins - Trimestral",
    "mininome": "DARFCOFINS",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 25,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 19,
    "nome": "DARF - CSLL - Cota",
    "mininome": "CSLL",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 31,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "Todo dia 31",
      "Todo dia 31",
      "Todo dia 31",
      "Todo dia 31",
      "Todo dia 31",
      "Todo dia 31",
      "Todo dia 31",
      "Todo dia 31",
      "Todo dia 31",
      "Todo dia 31",
      "Todo dia 31",
      "Todo dia 31"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 20,
    "nome": "DARF - CSLL - Trimestral",
    "mininome": "CSLL",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 25,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Último dia útil",
      "Não Tem",
      "Não Tem",
      "Último dia útil",
      "Não Tem",
      "Não Tem",
      "Último dia útil",
      "Não Tem",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 21,
    "nome": "DARF - CSLL - TRIMESTRAL - APLICAÇÃO",
    "mininome": "CSLL",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 24,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Último dia útil",
      "Não Tem",
      "Não Tem",
      "Todo dia 24",
      "Todo dia 24",
      "Todo dia 24",
      "Todo dia 24",
      "Todo dia 24",
      "Todo dia 24",
      "Todo dia 24",
      "Todo dia 24",
      "Todo dia 24"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 22,
    "nome": "DARF - IRPJ - Cota",
    "mininome": "IRPJ",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 31,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 31",
      "Todo dia 31",
      "Todo dia 31",
      "Todo dia 31",
      "Todo dia 31",
      "Todo dia 31",
      "Todo dia 31",
      "Todo dia 31",
      "Todo dia 31",
      "Todo dia 31",
      "Todo dia 31",
      "Todo dia 31"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 23,
    "nome": "DARF - IRPJ - Trimestral",
    "mininome": "IRPJ",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 25,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Último dia útil",
      "Não Tem",
      "Não Tem",
      "Último dia útil",
      "Não Tem",
      "Não Tem",
      "Último dia útil",
      "Não Tem",
      "Não Tem",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 24,
    "nome": "DARF - IRPJ - TRIMESTRAL - APLICAÇÃO",
    "mininome": "IRPJ",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 24,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Último dia útil",
      "Não Tem",
      "Não Tem",
      "Último dia útil",
      "Não Tem",
      "Não Tem",
      "Último dia útil",
      "Não Tem",
      "Todo dia 24",
      "Todo dia 24",
      "Todo dia 24",
      "Todo dia 24"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 25,
    "nome": "DARF - IRPJ - TRIMESTRAL - APLICAÇÃO",
    "mininome": "IRPJ",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 24,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Último dia útil",
      "Não Tem",
      "Não Tem",
      "Último dia útil",
      "Não Tem",
      "Não Tem",
      "Último dia útil",
      "Não Tem",
      "Todo dia 24",
      "Todo dia 24",
      "Todo dia 24",
      "Todo dia 24"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 26,
    "nome": "DARF - IRRF Retido Aluguel",
    "mininome": "DARF Alug.",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 20",
      "Todo dia 19",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 19",
      "Todo dia 20",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 27,
    "nome": "DARF - PIS - Trimestral",
    "mininome": "DARF - PIS",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 25,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 28,
    "nome": "DARF - RET",
    "mininome": "RET",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": true,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 29,
    "nome": "DAS - Mensal",
    "mininome": "PGDAS",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 30,
    "nome": "DAS MEI - Mensal",
    "mininome": "DAS MEI - ",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 31,
    "nome": "DASN - SIMEI - Dec. Anual Simples Nacional para o MEI",
    "mininome": "DASN MEI",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Último dia útil",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 32,
    "nome": "DCTFWEB - RECIBO",
    "mininome": "DCTFWEB",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 15,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": true,
    "ativa": false,
    "meses": [
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 33,
    "nome": "Declaração do Imposto sobre a Renda da Pessoa Física",
    "mininome": "DIRPF",
    "departamento": "Contábil",
    "responsavel": "Carlos Eduardo Araújo Marques Pimentel",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Último dia útil",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 34,
    "nome": "Declaração sociedade uni profissional",
    "mininome": "DSN",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Último dia útil"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 35,
    "nome": "DEFIS - Simples Nacional",
    "mininome": "DEFIS",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": true,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Não Tem",
      "Não Tem",
      "Último dia útil",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 36,
    "nome": "DEMOSTRATIVO FGTS RESCISORIO",
    "mininome": "GRRF",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 7,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 37,
    "nome": "DeSTDA",
    "mininome": "DeSTDA",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 38,
    "nome": "Diferencial de Aliquotas",
    "mininome": "DDA",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 3,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 03",
      "Todo dia 03",
      "Todo dia 03",
      "Todo dia 03",
      "Todo dia 03",
      "Todo dia 03",
      "Todo dia 03",
      "Todo dia 03",
      "Todo dia 03",
      "Todo dia 03",
      "Todo dia 03",
      "Todo dia 03"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 39,
    "nome": "Dime",
    "mininome": "DIME",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 10,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 40,
    "nome": "DIMOB - Declaração Informações Imobiliária",
    "mininome": "DIMOB",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 28,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Não Tem",
      "Todo dia 28",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 41,
    "nome": "DIPAM - PMSP",
    "mininome": "DIPAM - SP",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 16,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 16",
      "Todo dia 16",
      "Todo dia 16",
      "Todo dia 16",
      "Todo dia 16",
      "Todo dia 16",
      "Todo dia 16",
      "Todo dia 16",
      "Todo dia 16",
      "Todo dia 16",
      "Todo dia 16",
      "Todo dia 16"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 42,
    "nome": "DIRF - Declaração de Retenções",
    "mininome": "DIRF",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 28,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Não Tem",
      "Todo dia 28",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 43,
    "nome": "DIRF Declaração do Imposto Renda Retido na Fonte",
    "mininome": "DIRPF",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Não Tem",
      "Último dia útil",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 44,
    "nome": "DMED - Declaração Médicos e Odontólogos",
    "mininome": "DMED",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 28,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Não Tem",
      "Todo dia 28",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 45,
    "nome": "DMS - RELATORIO DE NOTAS FISCAIS NFSE",
    "mininome": "RL NFSe",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 10,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "10º dia útil",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 46,
    "nome": "DUAM ISS PROPRIO",
    "mininome": "DUAM ISS",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 10,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 47,
    "nome": "e-Social",
    "mininome": "e-Social",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 15,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 48,
    "nome": "EFD Contribuições - Mensal",
    "mininome": "EFD Cont",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 10,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 49,
    "nome": "EFD ICMS IPI",
    "mininome": "EFD ICMS",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 50,
    "nome": "EFD ICMSIPI",
    "mininome": "EFD ICMS",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": true,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 51,
    "nome": "EFD REINF",
    "mininome": "EFD REINF",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 15,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 52,
    "nome": "EMPREITEIROS",
    "mininome": "EMPREITEIR",
    "departamento": "Contábil",
    "responsavel": "Yasmin Larissa",
    "dia_vencimento": 10,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 53,
    "nome": "Extrato - 13 Adiantamento",
    "mininome": "Ext adiant",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 30,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Todo dia 30",
      "Não Tem"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 54,
    "nome": "Extrato - 13 Salário",
    "mininome": "13",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 55,
    "nome": "EXTRATO CONTA FGTS",
    "mininome": "EXTRATO",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 30,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 30",
      "Todo dia 30",
      "Todo dia 30",
      "Todo dia 30",
      "Todo dia 30",
      "Todo dia 30",
      "Todo dia 30",
      "Todo dia 30",
      "Todo dia 30",
      "Todo dia 30",
      "Todo dia 30",
      "Todo dia 30"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 56,
    "nome": "Extrato Mensal - Folha de Pagamento",
    "mininome": "Ext folha",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 7,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 57,
    "nome": "Extrato PGDAS",
    "mininome": "PGDAS",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": true,
    "alerta_guia": true,
    "ativa": false,
    "meses": [
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 58,
    "nome": "Extratos Bancários",
    "mininome": "EXTBANCO",
    "departamento": "Contábil",
    "responsavel": "Yasmin Larissa",
    "dia_vencimento": 10,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil",
      "10º dia útil"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 59,
    "nome": "FÉRIAS",
    "mininome": "FÉRIAS",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 7,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 07",
      "Todo dia 31",
      "Todo dia 31",
      "1º dia útil",
      "1º dia útil",
      "1º dia útil",
      "1º dia útil",
      "1º dia útil",
      "1º dia útil",
      "1º dia útil",
      "1º dia útil",
      "1º dia útil"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 60,
    "nome": "FGTS",
    "mininome": "FGTS",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 7,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": true,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 61,
    "nome": "FUNRURAL",
    "mininome": "FUNRURAL",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 62,
    "nome": "GIA",
    "mininome": "GIA",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 16,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Todo dia 16",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 63,
    "nome": "GRRF - GUIA DE RECOLHIMENTO RESCISORIO",
    "mininome": "GRRF",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 7,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "18º dia útil",
      "1º dia útil",
      "Todo dia 07",
      "Todo dia 01",
      "Todo dia 01",
      "Todo dia 07"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 64,
    "nome": "ICMS",
    "mininome": "ICMS",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 10,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 65,
    "nome": "ICMS Diferencial de Alíquota - DIFAL",
    "mininome": "DIFAL",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 66,
    "nome": "ICMS ST",
    "mininome": "ICMS ST",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 9,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 09",
      "Todo dia 09",
      "Todo dia 09",
      "Todo dia 09",
      "Todo dia 09",
      "Todo dia 09",
      "Todo dia 09",
      "Todo dia 09",
      "Todo dia 09",
      "Todo dia 09",
      "Todo dia 09",
      "Todo dia 09"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 67,
    "nome": "Informe de rendimento",
    "mininome": "INFORME",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 28,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "Não Tem",
      "Todo dia 28",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 68,
    "nome": "INSS - IRRF",
    "mininome": "INSS",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": true,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 69,
    "nome": "INSS - Serviços Prestado",
    "mininome": "INSS PREST",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 70,
    "nome": "INSS - Serviços Tomados",
    "mininome": "IRRF PRET",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 71,
    "nome": "INSS s 13 Salário",
    "mininome": "INSS s 13",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 72,
    "nome": "IRRF - Salário",
    "mininome": "IRRF",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 73,
    "nome": "IRRF - Serviços Tomados",
    "mininome": "IRRF PRET",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 74,
    "nome": "ISS - Retido da Fonte",
    "mininome": "DUAM ISS",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 10,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 75,
    "nome": "MARKETING",
    "mininome": "MARKETING",
    "departamento": "Contábil",
    "responsavel": "Yasmin Larissa",
    "dia_vencimento": 15,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "15º dia útil",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 76,
    "nome": "Memória de Calculo Simples Nacional",
    "mininome": "Calculo NS",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 77,
    "nome": "Parcelamento - ICMS Auto de Infração",
    "mininome": "PAR ICMS",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 25,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": true,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 78,
    "nome": "Parcelamento ICMS",
    "mininome": "PARC ICMS",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 25,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": true,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25",
      "Todo dia 25"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 79,
    "nome": "Parcelamento INSS DAU",
    "mininome": "Parcelamen",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 80,
    "nome": "Parcelamento INSS Intimação",
    "mininome": "Parcelamen",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 81,
    "nome": "PARCELAMENTO RECEITA FEDERAL",
    "mininome": "PARCELAMEN",
    "departamento": "Bancos",
    "responsavel": "Indefinido",
    "dia_vencimento": 15,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "Não Tem",
      "Não Tem",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15",
      "Todo dia 15"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 82,
    "nome": "PARCELAMENTO SIMPLES NACIONAL",
    "mininome": "PARCELAMEN",
    "departamento": "Bancos",
    "responsavel": "Indefinido",
    "dia_vencimento": 5,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": true,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 83,
    "nome": "Pro labore",
    "mininome": "Pro labore",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 5,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 84,
    "nome": "Recibo de Pagamento",
    "mininome": "Folha Pag",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 5,
    "competencia": "Sim",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 85,
    "nome": "Recibo de Pagamento - 13º Adiantamento",
    "mininome": "Recibo de ",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Último dia útil",
      "Não Tem"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 86,
    "nome": "Recibo de Pagamento - 13º Salário",
    "mininome": "13 SALÁRIO",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 87,
    "nome": "Recibo PGDAS",
    "mininome": "REC PGDAS",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": true,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 88,
    "nome": "Relação Geral dos Líquidos - 13o Adiantamento",
    "mininome": "13 Adian",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 30,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Todo dia 30",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 89,
    "nome": "Relação Geral dos Líquidos - 13o Adiantamento",
    "mininome": "13 Adian",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 30,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Todo dia 30",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 90,
    "nome": "Relação Geral dos Líquidos - 13o Integral",
    "mininome": "13 Integra",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 91,
    "nome": "Relatorio Ferias",
    "mininome": "Rel Ferias",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 2,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "Todo dia 02",
      "Todo dia 02",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil",
      "Último dia útil"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 92,
    "nome": "Relatório FGTS",
    "mininome": "FGTS",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 7,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 93,
    "nome": "Relatório Liquido Folha",
    "mininome": "RL-Liquido",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 7,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 07",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil",
      "5º dia útil"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 94,
    "nome": "REQ SEGURO DESEMPREGO",
    "mininome": "SEG-DESEMP",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 7,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 07",
      "Todo dia 30",
      "Todo dia 30",
      "Todo dia 30",
      "Todo dia 30",
      "Todo dia 30"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 95,
    "nome": "REST - Relação de Serviços de Terceiros",
    "mininome": "REST",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 10,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10",
      "Todo dia 10"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 96,
    "nome": "SPED ECD - Escrituração Contábil Digital",
    "mininome": "ECD",
    "departamento": "Contábil",
    "responsavel": "Carlos Eduardo Araújo Marques Pimentel",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Último dia útil",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 97,
    "nome": "SPED ECF - Escrituração Contábil Fiscal",
    "mininome": "ECF - Cont",
    "departamento": "Contábil",
    "responsavel": "Carlos Eduardo Araújo Marques Pimentel",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": false,
    "ativa": true,
    "meses": [
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Último dia útil",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 98,
    "nome": "SPED Livros Fiscais de Saídas",
    "mininome": "SPED",
    "departamento": "Contábil",
    "responsavel": "Carlos Eduardo Araújo Marques Pimentel",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": true,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20",
      "Todo dia 20"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 99,
    "nome": "TAXA DE LICENCA PARA FUNCIONAMENTO",
    "mininome": "TX LICENÇA",
    "departamento": "Fiscal",
    "responsavel": "Gleidson Tavares",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "Todo dia 20",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  },
  {
    "id": 100,
    "nome": "Termo de Rescisão de Contrato de Trabalho",
    "mininome": "TRCT",
    "departamento": "Pessoal",
    "responsavel": "Luciene Alves",
    "dia_vencimento": 20,
    "competencia": "Não",
    "exigir_robo": false,
    "passivel_multa": false,
    "alerta_guia": true,
    "ativa": true,
    "meses": [
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem",
      "Não Tem"
    ],
    "empresas": [],
    "tributacoes": [],
    "whatsapp": false
  }
];
