/**
 * EPimentel - Relatorios PDF/Excel
 */
import * as XLSX from 'xlsx'
import jsPDF from 'jspdf'
import 'jspdf-autotable'
import { useState } from 'react'

const NAVY=[27,42,74],GOLD=[197,165,90],GRAY=[245,245,245],WHITE=[255,255,255]
const agora=()=>new Date().toLocaleString('pt-BR')
const hoje=()=>new Date().toLocaleDateString('pt-BR')
const hexRgb=h=>[parseInt(h.slice(1,3),16),parseInt(h.slice(3,5),16),parseInt(h.slice(5,7),16)]

function cab(doc,t,s,l=210){doc.setFillColor(...NAVY);doc.rect(0,0,l,24,'F');doc.setFillColor(...GOLD);doc.roundedRect(9,5,14,14,2,2,'F');doc.setTextColor(...NAVY);doc.setFontSize(10);doc.setFont('helvetica','bold');doc.text('EP',16,14.5,{align:'center'});doc.setTextColor(...GOLD);doc.setFontSize(11);doc.setFont('helvetica','bold');doc.text('EPimentel',27,10.5);doc.setTextColor(180,160,120);doc.setFontSize(7);doc.text('Auditoria & Contabilidade',27,15.5);doc.setTextColor(...WHITE);doc.setFontSize(13);doc.setFont('helvetica','bold');doc.text(t,l/2,11,{align:'center'});if(s){doc.setFontSize(8);doc.setTextColor(180,200,230);doc.text(s,l/2,17,{align:'center'})};doc.setTextColor(150,170,200);doc.setFontSize(7);doc.text(agora(),l-9,17,{align:'right'});return 28}

function rod(doc,pg,tot,l=210){doc.setFillColor(...GRAY);doc.rect(0,285,l,12,'F');doc.setDrawColor(220,220,220);doc.line(0,285,l,285);doc.setTextColor(160,160,160);doc.setFontSize(7);doc.setFont('helvetica','normal');doc.text('CRC/GO 026.994/O-8 | EPimentel',l/2,290.5,{align:'center'});doc.text('Pg '+pg+'/'+tot,l-9,290.5,{align:'right'})}

function cds(doc,d,y,l=210){if(!d||!d.length)return y;const cw=(l-16)/d.length,ch=16;d.forEach((x,i)=>{const px=8+i*cw;doc.setFillColor(...(x.cor?hexRgb(x.cor):[240,248,255]));doc.roundedRect(px,y,cw-2,ch,2,2,'F');doc.setTextColor(...NAVY);doc.setFontSize(15);doc.setFont('helvetica','bold');doc.text(String(x.valor),px+cw/2-1,y+9.5,{align:'center'});doc.setFontSize(7);doc.setFont('helvetica','normal');doc.setTextColor(100,100,100);doc.text(x.label,px+cw/2-1,y+14,{align:'center'})});return y+ch+6}

export function graficoBarrasH(doc,d,y,t,l=210){if(!d||!d.length)return y;const mv=Math.max(...d.map(x=>x.valor))||1,mw=l-90,bh=9,g=4;if(t){doc.setFontSize(9);doc.setFont('helvetica','bold');doc.setTextColor(...NAVY);doc.text(t,8,y+5);y+=8};d.forEach((x,i)=>{const ry=y+i*(bh+g),bw=Math.max((x.valor/mv)*mw,1),rgb=x.cor?hexRgb(x.cor):GOLD;doc.setFontSize(7.5);doc.setFont('helvetica','normal');doc.setTextColor(80,80,80);doc.text((x.label||'').substring(0,20),8,ry+bh/2+2.5,{align:'left'});doc.setFillColor(230,230,230);doc.roundedRect(60,ry,mw,bh,1.5,1.5,'F');doc.setFillColor(...rgb);doc.roundedRect(60,ry,bw,bh,1.5,1.5,'F');doc.setTextColor(60,60,60);doc.text(String(x.valor),62+mw,ry+bh/2+2.5)});return y+d.length*(bh+g)+6}

export function exportarPDF(o){const doc=new jsPDF({orientation:o.orientacao||'portrait',unit:'mm',format:'a4'});const l=(o.orientacao||'portrait')==='landscape'?297:210;let y=cab(doc,o.titulo,o.subtitulo||'',l);if(o.resumo&&o.resumo.length)y=cds(doc,o.resumo,y,l);if(o.grafico&&o.grafico.length)y=graficoBarrasH(doc,o.grafico,y,o.graficoTitulo||'',l);doc.autoTable({startY:y,head:[o.colunas.map(c=>c.header)],body:o.linhas.map(r=>o.colunas.map(c=>{const v=r[c.dataKey];return v!=null?String(v):''})),styles:{fontSize:8,cellPadding:2.5,overflow:'linebreak',font:'helvetica'},headStyles:{fillColor:NAVY,textColor:GOLD,fontStyle:'bold',fontSize:8.5},alternateRowStyles:{fillColor:[249,250,251]},columnStyles:Object.fromEntries(o.colunas.map((c,i)=>[i,{cellWidth:c.width||'auto'}])),margin:{left:8,right:8},didDrawPage:d=>{rod(doc,d.pageNumber,doc.internal.getNumberOfPages(),l)}});doc.save(o.nomeArquivo||('rel_'+Date.now()+'.pdf'))}

export function exportarExcel(o){const wb=XLSX.utils.book_new(),r=o.resumo||[];const ws=XLSX.utils.aoa_to_sheet([['EPimentel'],['Rel: '+o.titulo],['Gerado: '+agora()],['CRC/GO 026.994/O-8'],[],
...(r.length?[r.map(x=>x.label),r.map(x=>x.valor),[]]:[] ),
o.colunas.map(c=>c.header),...o.linhas.map(l=>o.colunas.map(c=>{const v=l[c.dataKey];return v!=null?v:''}))]);ws['!cols']=o.colunas.map(c=>({wch:c.excelWidth||18}));XLSX.utils.book_append_sheet(wb,ws,o.titulo.substring(0,30));(o.abasExtras||[]).forEach(a=>{const we=XLSX.utils.aoa_to_sheet([a.colunas.map(c=>c.header),...a.linhas.map(l=>a.colunas.map(c=>{const v=l[c.dataKey];return v!=null?v:''}))]);we['!cols']=a.colunas.map(c=>({wch:c.excelWidth||16}));XLSX.utils.book_append_sheet(wb,we,a.nome.substring(0,30))});XLSX.writeFile(wb,o.nomeArquivo||('rel_'+Date.now()+'.xlsx'))}

export function BotaoRelatorio({onPDF,onExcel,label,small}){label=label||'Relatorio';const [open,setOpen]=useState(false);const p=small?{padding:'4px 10px',fontSize:11}:{padding:'7px 14px',fontSize:12};return(<div style={{position:'relative',display:'inline-block'}}><button onClick={()=>setOpen(v=>!v)} style={{...p,borderRadius:8,background:'#1B2A4A',color:'#C5A55A',border:'none',cursor:'pointer',fontWeight:700,display:'flex',alignItems:'center',gap:6}}>{label}</button>{open&&(<><div style={{position:'fixed',inset:0,zIndex:49}} onClick={()=>setOpen(false)}/><div style={{position:'absolute',top:'100%',right:0,zIndex:50,background:'#fff',border:'1px solid #e8e8e8',borderRadius:10,boxShadow:'0 4px 20px rgba(0,0,0,.12)',padding:6,minWidth:160,marginTop:4}}><button onClick={()=>{onPDF();setOpen(false)}} style={{width:'100%',padding:'8px 12px',borderRadius:7,background:'none',border:'none',cursor:'pointer',fontSize:12,textAlign:'left',color:'#dc2626',fontWeight:600}}>PDF</button><button onClick={()=>{onExcel();setOpen(false)}} style={{width:'100%',padding:'8px 12px',borderRadius:7,background:'none',border:'none',cursor:'pointer',fontSize:12,textAlign:'left',color:'#16a34a',fontWeight:600}}>Excel</button></div></>)}</div>)}
